# Generated by Django 4.2.7 on 2025-07-26 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0017_image__transparent'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('question', models.CharField(max_length=500, verbose_name='Câu hỏi')),
                ('answer', models.TextField(verbose_name='Câu trả lời')),
                ('category', models.CharField(choices=[('admission', 'Tuyển sinh'), ('tuition', 'Học phí'), ('curriculum', 'Chương trình học'), ('facilities', 'Cơ sở vật chất'), ('health', 'Sức khỏe'), ('other', 'Khác')], default='other', max_length=50, verbose_name='Danh mục')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự')),
            ],
            options={
                'verbose_name': 'Câu hỏi thường gặp',
                'verbose_name_plural': 'Câu hỏi thường gặp',
                'ordering': ['order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('name', models.CharField(max_length=200, verbose_name='Tên trường')),
                ('slogan', models.CharField(blank=True, max_length=300, verbose_name='Slogan')),
                ('description', models.TextField(verbose_name='Mô tả về trường')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('working_hours', models.CharField(default='7:00 - 18:00', max_length=100, verbose_name='Giờ hoạt động')),
                ('working_days', models.CharField(default='Thứ 2 - Thứ 6', max_length=100, verbose_name='Ngày hoạt động')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('brochure', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_brochures', to='filer.file', verbose_name='Brochure (PDF)')),
                ('hero_image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_hero_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Hình ảnh chính')),
                ('logo', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_logos', to=settings.FILER_IMAGE_MODEL, verbose_name='Logo trường')),
            ],
            options={
                'verbose_name': 'Thông tin trường',
                'verbose_name_plural': 'Thông tin trường',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('category', models.CharField(choices=[('classroom', 'Lớp học'), ('playground', 'Sân chơi'), ('activities', 'Hoạt động'), ('events', 'Sự kiện'), ('meals', 'Bữa ăn')], default='activities', max_length=50, verbose_name='Danh mục')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Hình ảnh')),
            ],
            options={
                'verbose_name': 'Hình ảnh',
                'verbose_name_plural': 'Thư viện ảnh',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('title', models.CharField(max_length=200, verbose_name='Tên giải thưởng')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('year', models.IntegerField(verbose_name='Năm')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievement_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Hình ảnh')),
            ],
            options={
                'verbose_name': 'Thành tích',
                'verbose_name_plural': 'Thành tích & Giải thưởng',
                'ordering': ['-year', 'title'],
            },
        ),
    ]
