# Generated by Django 4.2.7 on 2025-07-27 09:16

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_herosetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosetting',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('background', '1534x512', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='herosetting',
            name='background',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='hero_backgrounds/', verbose_name='Ảnh nền Hero'),
        ),
    ]
