# Generated by Django 4.2.7 on 2025-07-27 09:47

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_herosetting_cropping_alter_herosetting_background'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herosetting',
            options={'verbose_name': 'Cài đặt Hero', 'verbose_name_plural': 'Cài đặt Hero'},
        ),
        migrations.AlterField(
            model_name='herosetting',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('background', '1534x512', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
    ]
