# Generated by Django 4.2.7 on 2025-07-27 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_herosetting_options_alter_herosetting_cropping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herosetting',
            options={},
        ),
    ]
