# Generated by Django 4.2.7 on 2025-07-27 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('core', '0005_alter_herosetting_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('subtitle', models.TextField(max_length=500, verbose_name='Mô tả')),
                ('background', image_cropping.fields.ImageCropField(help_text='Tỉ lệ khuyến nghị: 1920x1080', upload_to='hero_slides/', verbose_name='Ảnh nền')),
                ('cropping', image_cropping.fields.ImageRatioField('background', '1920x1080', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping')),
                ('primary_button_text', models.CharField(default='Đăng ký tham quan', max_length=50, verbose_name='Text nút chính')),
                ('primary_button_link', models.CharField(default='#contact', max_length=200, verbose_name='Link nút chính')),
                ('secondary_button_text', models.CharField(blank=True, max_length=50, verbose_name='Text nút phụ')),
                ('secondary_button_link', models.CharField(blank=True, max_length=200, verbose_name='Link nút phụ')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='herosetting',
            options={'verbose_name': 'Hero Setting (Cũ)', 'verbose_name_plural': 'Hero Settings (Cũ)'},
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('parent_name', models.CharField(max_length=200, verbose_name='Tên phụ huynh')),
                ('child_name', models.CharField(max_length=200, verbose_name='Tên con')),
                ('child_class', models.CharField(max_length=100, verbose_name='Lớp')),
                ('content', models.TextField(verbose_name='Nội dung đánh giá')),
                ('rating', models.IntegerField(choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], default=5, verbose_name='Đánh giá')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('parent_photo', filer.fields.image.FilerImageField(blank=True, help_text='Tỉ lệ khuyến nghị: vuông 200x200', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonial_photos', to=settings.FILER_IMAGE_MODEL, verbose_name='Ảnh phụ huynh')),
            ],
            options={
                'verbose_name': 'Đánh giá phụ huynh',
                'verbose_name_plural': 'Đánh giá phụ huynh',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('name', models.CharField(max_length=200, verbose_name='Họ tên')),
                ('role', models.CharField(max_length=200, verbose_name='Chức vụ')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Điện thoại')),
                ('experience_years', models.IntegerField(default=0, verbose_name='Số năm kinh nghiệm')),
                ('education', models.TextField(blank=True, verbose_name='Học vấn')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='Chuyên môn')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('photo', filer.fields.image.FilerImageField(blank=True, help_text='Tỉ lệ khuyến nghị: vuông 400x400', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_photos', to=settings.FILER_IMAGE_MODEL, verbose_name='Ảnh đại diện')),
            ],
            options={
                'verbose_name': 'Giáo viên',
                'verbose_name_plural': 'Đội ngũ giáo viên',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('name', models.CharField(max_length=200, verbose_name='Tên chương trình')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('age_range', models.CharField(max_length=50, verbose_name='Độ tuổi')),
                ('icon', models.CharField(default='📚', help_text='Emoji hoặc ký tự đặc biệt', max_length=10, verbose_name='Icon')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='Thời gian học')),
                ('class_size', models.IntegerField(default=15, verbose_name='Sĩ số lớp')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('image', filer.fields.image.FilerImageField(blank=True, help_text='Tỉ lệ khuyến nghị: 400x300', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Ảnh chương trình')),
            ],
            options={
                'verbose_name': 'Chương trình học',
                'verbose_name_plural': 'Chương trình học',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('meta_title', models.CharField(blank=True, help_text='Tối đa 60 ký tự', max_length=60, verbose_name='Tiêu đề SEO')),
                ('meta_description', models.TextField(blank=True, help_text='Tối đa 160 ký tự', max_length=160, verbose_name='Mô tả SEO')),
                ('meta_keywords', models.CharField(blank=True, help_text='Các từ khóa cách nhau bằng dấu phẩy', max_length=255, verbose_name='Từ khóa SEO')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(unique=True, verbose_name='Đường dẫn')),
                ('excerpt', models.TextField(max_length=300, verbose_name='Mô tả ngắn')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('author', models.CharField(default='Admin', max_length=100, verbose_name='Tác giả')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('category', models.CharField(choices=[('news', 'Tin tức'), ('events', 'Sự kiện'), ('activities', 'Hoạt động'), ('announcements', 'Thông báo')], default='news', max_length=50, verbose_name='Danh mục')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('thumbnail', filer.fields.image.FilerImageField(blank=True, help_text='Tỉ lệ khuyến nghị: 400x300', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_thumbnails', to=settings.FILER_IMAGE_MODEL, verbose_name='Ảnh thumbnail')),
            ],
            options={
                'verbose_name': 'Tin tức',
                'verbose_name_plural': 'Tin tức & Bài viết',
                'ordering': ['-publish_date'],
            },
        ),
    ]
