# Generated by Django 4.2.7 on 2025-07-27 13:29

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_heroslide_alter_herosetting_options_testimonial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='background',
            field=image_cropping.fields.ImageCropField(help_text='Tỉ lệ khuyến nghị: 1920x1080. Có thể crop sau khi upload.', upload_to='hero_slides/', verbose_name='Ảnh nền'),
        ),
    ]
